### ISSUE TITLE
first login in the dashboard

### ISSUE THREAD

**Issue by denon2002** [multunus/onemdm-server#4]
Hy, 

a have all installed. And now i see the Login for the dashboard.
the table with admin_users is empty.

How login into the dashboard ?

**Comment by leenasn** [comment]
@denon2002 you can run the command `rake db:seed`, which will create an admin user. The username will be 'admin@example.com' with the password as 'password'.

If you prefer to change these, change the same in the file 'db/seeds.rb' before running `rake db:seed` command.

**Comment by denon2002** [comment]
thanks

**Comment by leenasn** [comment]
@denon2002 Assuming that you were looking at an MDM solution, can you let me know the following? This helps us to improve OneMDM further:

- What are your MDM requirements?
- Did OneMDM solve fit your requirements? 

Thanks,

**Comment by denon2002** [comment]
Hy,

I will answer you as soon as I solved the following problem.
The server is now running and i can login. Ok,...
Now, i will create the android apk. 

I habe installed the android sdk, but during the process always comes following message..
[ausgabe.txt](https://github.com/multunus/onemdm-server/files/508776/ausgabe.txt)

Can you help me ?

**Comment by leenasn** [comment]
@denon2002 looks like you are missing the dependencies for android like the play services, build tools, app combat etc. You can look at the [wercker.yml](https://github.com/multunus/onemdm-client/blob/master/wercker.yml) to see the dependencies that we've given for wercker build to get an idea.

**Comment by denon2002** [comment]
Hy, i have solved this problem. I have installed the completet Android-sdk.
Now i could generated the apk.
