### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by grego1981** [multunus/onemdm-server#7]
Hello I'm trying to install oneMDM as per instructions, but when I get to rake db:migrate I get the following errors:

/root/onemdm-server/config/environments/development.rb:45: warning: already initialized constant DEFAULT_APP_URL
/root/onemdm-server/config/application.rb:41: warning: previous definition of DEFAULT_APP_URL was here
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar/rake.rb:23:in `patch?'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar/rake.rb:6:in `patch!'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar/rake.rb:38:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar.rb:788:in `require_hooks'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar.rb:753:in `configure'
/root/onemdm-server/config/initializers/rollbar.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/root/onemdm-server/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

How can solve this? The system I'm running it on is Ubuntu 16.04

Thank you!

**Comment by leenasn** [comment]
Seems the problem is with Rollbar, the error tracking tool we are using as mentioned in their Issues list here:

[https://github.com/rollbar/rollbar-gem/issues/396](https://github.com/rollbar/rollbar-gem/issues/396)

Can you try the following:

 - If you are not using bundle exec for running the rake commands can you try that i.e. execute the command `bundle exec rake db:migrate` ?
 - If the problem still exists,  can you upgrade rollbar to the latest version and try?

Thanks

**Comment by grego1981** [comment]
Tried it to no avail, also updated rollabar with `bundle update rollbar` the output in both circumstances is

root@itsrv-02:~/onemdm-server# bundle exec rake db:migrate
/root/onemdm-server/config/environments/development.rb:45: warning: already initialized constant DEFAULT_APP_URL
/root/onemdm-server/config/application.rb:41: warning: previous definition of DEFAULT_APP_URL was here
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar/rake.rb:23:in `patch?'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar/rake.rb:6:in `patch!'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar/rake.rb:38:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar.rb:788:in `require_hooks'
/var/lib/gems/2.3.0/gems/rollbar-2.5.2/lib/rollbar.rb:753:in `configure'
/root/onemdm-server/config/initializers/rollbar.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/root/onemdm-server/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by leenasn** [comment]
@grego1981 I've upgraded rollbar to the latest version [2.14.0] in Gemfile. Can you try again? It should fix the issue I believe. Can you let me know?

Can you also let me know what is the rake version you are using?

**Comment by grego1981** [comment]
Yes it now works! Thank you!

**Comment by leenasn** [comment]
Great to hear that it is resolved @grego1981.
