### ISSUE TITLE
Device not connecting 

### ISSUE THREAD

**Issue by grego1981** [multunus/onemdm-server#8]
Hello, I have installed the server and trying to create the app.  I've run the ./gradlew clean installDebug and 2 apks were created, I've installed the debug apk and ran it but nothing happened, no device was added to the console. Below is the config.java content:

> package com.multunus.onemdm.config;
> 
> import android.os.Build;
> import android.app.AlarmManager;
> 
> import com.multunus.onemdm.BuildConfig;
> 
> final public class Config {
>     public static final String ACCESS_TOKEN = "access_token";
>     public static final String HOST_URL = (BuildConfig.DEBUG)? "http://xx.xx.xx.xx:3000"
>         : "http://xx.xx.xx.xx:3000"; //"http://192.168.2.92:3000/";
>     public static final String REGISTRATION_URL = HOST_URL + "devices";
>     public static final String HEARTBEAT_URL = HOST_URL + "heartbeats";
>     public static final String APP_USAGE_TRACKING_URL = HOST_URL + "app_usages";
>     public static final String APP_INSTALLED_URL = HOST_URL + "installations/installed";
>     public static final long USAGE_COLLECTION_TRACKING_INTERVAL_IN_SECONDS = 2;
>     public static final long USAGE_SYNCING_INTERVAL = AlarmManager.INTERVAL_HALF_DAY;
> 
> 
>     public static String PREFERENCE_TAG = "onemdm";
>     public static final int DEFAULT_HEARTBEAT_RETRY_INTERVAL = 30;
>     public static final String GCM_SENDER_ID = "958182646350";
>     public static final String APP_DATA = "APP_DATA";
>     public static final int MAX_COUNT_OF_DATA_TO_BE_SYNCED = 100;
> 
>     //Feature Flag(s)
> 
>     public static final boolean TRACK_APP_USAGE = android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP;
> 
> 
>     private Config(){
> 
>     }
> }

**Comment by leenasn** [comment]
@grego1981 can you change the HOST_URL to your local server address? You can change it to something like this:

Replace HOST_URL variable with something like as follows:

public static final String HOST_URL = "http://<local-ip>:3000/";

Replace _<local-ip>_ with your local server address. 

It should have shown an error in the android side, wondering why it didn't.

**Comment by grego1981** [comment]
It's Ok, I've changed the value as shown. I've connected the device. Looking forward to see how the system works! Thank you!
